<?php

namespace ContainerYwJUR0U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0YQEsXgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0YQEsXg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0YQEsXg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'policy1' => ['privates', '.errored..service_locator.0YQEsXg.App\\Entity\\Policy1', NULL, 'Cannot autowire service ".service_locator.0YQEsXg": it needs an instance of "App\\Entity\\Policy1" but this type has been excluded in "config/services.yaml".'],
        ], [
            'policy1' => 'App\\Entity\\Policy1',
        ]);
    }
}
