<?php

namespace ContainerYwJUR0U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NnqCUHtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nnqCUHt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nnqCUHt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'policy1Repository' => ['privates', 'App\\Repository\\Policy1Repository', 'getPolicy1RepositoryService', true],
        ], [
            'policy1Repository' => 'App\\Repository\\Policy1Repository',
        ]);
    }
}
