<?php

namespace ContainerYwJUR0U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPolicy12Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.FeF82Gz.App\Entity\Policy1' shared service.
     *
     * @return \App\Entity\Policy1
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.FeF82Gz": it needs an instance of "App\\Entity\\Policy1" but this type has been excluded in "config/services.yaml".');
    }
}
