<?php

namespace ContainerYwJUR0U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPoliciesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Policies' shared autowired service.
     *
     * @return \App\Service\Policies
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Policies.php';

        return $container->privates['App\\Service\\Policies'] = new \App\Service\Policies(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')));
    }
}
