<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerII5CMec\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerII5CMec/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerII5CMec.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerII5CMec\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerII5CMec\App_KernelDevDebugContainer([
    'container.build_hash' => 'II5CMec',
    'container.build_id' => 'c3f10fb4',
    'container.build_time' => 1706234244,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerII5CMec');
