<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'service_policy_create' => [[], ['_controller' => 'App\\Controller\\AjaxServiceController::saveData'], [], [['text', '/service/policy/create']], [], [], []],
    'app_list' => [[], ['_controller' => 'App\\Controller\\ListController::index'], [], [['text', '/policies']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\LoginController::logout'], [], [['text', '/logout']], [], [], []],
    'app_policy1' => [[], ['_controller' => 'App\\Controller\\Policy1Controller::List'], [], [['text', '/api/policy-v1']], [], [], []],
    'policy1_show' => [['id'], ['_controller' => 'App\\Controller\\Policy1Controller::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/policy1']], [], [], []],
    'policy1_create' => [[], ['_controller' => 'App\\Controller\\Policy1Controller::create'], [], [['text', '/api/policy-v1/create']], [], [], []],
    'policy1_update' => [['id'], ['_controller' => 'App\\Controller\\Policy1Controller::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/policy1/update']], [], [], []],
    'policy1_delete' => [['id'], ['_controller' => 'App\\Controller\\Policy1Controller::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/policy1']], [], [], []],
    'policy1_user_details' => [['id'], ['_controller' => 'App\\Controller\\Policy1Controller::showUserPolicy'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/policy-v1/user']], [], [], []],
    'registration' => [[], ['_controller' => 'App\\Controller\\RegistrationController::index'], [], [['text', '/registration']], [], [], []],
    'app_login2' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login2']], [], [], []],
    'app_logout2' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout2']], [], [], []],
    'App\Controller\AjaxServiceController::saveData' => [[], ['_controller' => 'App\\Controller\\AjaxServiceController::saveData'], [], [['text', '/service/policy/create']], [], [], []],
    'App\Controller\ListController::index' => [[], ['_controller' => 'App\\Controller\\ListController::index'], [], [['text', '/policies']], [], [], []],
    'App\Controller\LoginController::login' => [[], ['_controller' => 'App\\Controller\\LoginController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\LoginController::logout' => [[], ['_controller' => 'App\\Controller\\LoginController::logout'], [], [['text', '/logout']], [], [], []],
    'App\Controller\Policy1Controller::List' => [[], ['_controller' => 'App\\Controller\\Policy1Controller::List'], [], [['text', '/api/policy-v1']], [], [], []],
    'App\Controller\Policy1Controller::show' => [['id'], ['_controller' => 'App\\Controller\\Policy1Controller::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/policy1']], [], [], []],
    'App\Controller\Policy1Controller::create' => [[], ['_controller' => 'App\\Controller\\Policy1Controller::create'], [], [['text', '/api/policy-v1/create']], [], [], []],
    'App\Controller\Policy1Controller::update' => [['id'], ['_controller' => 'App\\Controller\\Policy1Controller::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/policy1/update']], [], [], []],
    'App\Controller\Policy1Controller::delete' => [['id'], ['_controller' => 'App\\Controller\\Policy1Controller::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/policy1']], [], [], []],
    'App\Controller\Policy1Controller::showUserPolicy' => [['id'], ['_controller' => 'App\\Controller\\Policy1Controller::showUserPolicy'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/policy-v1/user']], [], [], []],
    'App\Controller\RegistrationController::index' => [[], ['_controller' => 'App\\Controller\\RegistrationController::index'], [], [['text', '/registration']], [], [], []],
    'App\Controller\SecurityController::login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login2']], [], [], []],
    'App\Controller\SecurityController::logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout2']], [], [], []],
];
